import { z } from "zod";

export const carUpdateSchema = z.object({
  name: z.string().min(1),
  imageKey: z.string().trim().nullable().optional().transform((value) => value || null),
  brand: z.string().min(1),
  segment: z.string().min(1),
  origin: z.string().min(1),
  releaseYear: z.coerce.number().int().positive(),
  platform: z.string().min(1),
  drivetrain: z.string().min(1),
  frontSuspension: z.string().min(1),
  rearSuspension: z.string().min(1),
  engine: z.string().min(1),
  engineHp: z.coerce.number().int().nonnegative(),
  torque: z.coerce.number().int().nonnegative(),
  transmission: z.string().min(1),
  fuelConsumption: z.coerce.number().positive(),
  batteryType: z.string().min(1),
  batteryCapacity: z.coerce.number().nonnegative(),
  acceleration0100: z.coerce.number().nonnegative(),
  price: z.coerce.number().int().nonnegative().transform(BigInt),
  basePrice: z.coerce.number().int().nonnegative().transform(BigInt),
  topPrice: z.coerce.number().int().nonnegative().transform(BigInt),
  seats: z.coerce.number().int().positive(),
  groundClearance: z.coerce.number().int().nonnegative(),
  length: z.coerce.number().int().positive(),
  width: z.coerce.number().int().positive(),
  height: z.coerce.number().int().positive(),
  wheelbase: z.coerce.number().int().positive(),
  curbWeight: z.coerce.number().int().nonnegative(),
  grossWeight: z.coerce.number().int().nonnegative(),
  turningRadius: z.coerce.number().nonnegative(),
  cargoVolume: z.coerce.number().int().nonnegative(),
  fuelTankCapacity: z.coerce.number().int().nonnegative(),
  frontBrake: z.string().min(1),
  rearBrake: z.string().min(1),
  tireWheel: z.string().min(1),
  ledHeadlights: z.boolean(),
  autoHeadlights: z.boolean(),
  electricMirrors: z.boolean(),
  sunroof: z.boolean(),
  screenSize: z.coerce.number().positive(),
  appleCarplay: z.boolean(),
  androidAuto: z.boolean(),
  bluetooth: z.boolean(),
  usb: z.boolean(),
  speakers: z.coerce.number().int().nonnegative(),
  wirelessCharging: z.boolean(),
  leatherSeats: z.boolean(),
  cabinSpace: z.string().min(1),
  electricParkingBrake: z.boolean(),
  autoHold: z.boolean(),
  hud: z.boolean(),
  driveModes: z.boolean(),
  paddleShifters: z.boolean(),
  cruiseControl: z.boolean(),
  adaptiveCruiseControl: z.boolean(),
  airbags: z.coerce.number().int().nonnegative(),
  absEbd: z.boolean(),
  brakeAssist: z.boolean(),
  esp: z.boolean(),
  tractionControl: z.boolean(),
  hillStartAssist: z.boolean(),
  blindSpotWarning: z.boolean(),
  rearCamera: z.boolean(),
  camera360: z.boolean(),
  laneAssist: z.boolean(),
  aeb: z.boolean(),
  rearCrossTrafficAlert: z.boolean(),
  tirePressureMonitoring: z.boolean(),
  parkingSensors: z.boolean(),
  isofix: z.boolean(),
  safety: z.string().min(1)
});

export type CarUpdateInput = z.infer<typeof carUpdateSchema>;
